In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

print("Welcome to MatchLens ⚽")
print("Pandas version:", pd.__version__)

import pandas as pd

df = pd.read_csv("../data/epl_player_stats_24_25.csv")

df.head()

Welcome to MatchLens ⚽
Pandas version: 3.0.3

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
0,Ben White,Arsenal,England,DEF,17,1198,0,2,9,12,...,10,2,0,0,0%,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
2,David Raya,Arsenal,Spain,GKP,38,3420,0,0,0,0,...,1,3,0,86,72%,0,0,8,53,2.1
3,Declan Rice,Arsenal,England,MID,35,2833,4,7,48,18,...,21,5,1,0,0%,0,0,0,0,0.0
4,Ethan Nwaneri,Arsenal,England,MID,26,889,4,0,24,0,...,9,1,0,0,0%,0,0,0,0,0.0

In [35]:
df["Position"].unique()

<ArrowStringArray>
['DEF', 'MID', 'GKP', 'FWD']
Length: 4, dtype: str

In [42]:
df[df["Goals"]>10][["Player Name", "Club", "Goals"]]

              Player Name                     Club  Goals
46          Ollie Watkins              Aston Villa     16
82           Bryan Mbeumo                Brentford     20
107           Yoane Wissa                Brentford     19
141           Cole Palmer                  Chelsea     15
180  Jean-Philippe Mateta           Crystal Palace     14
324         Mohamed Salah                Liverpool     29
335        Erling Haaland          Manchester City     22
391        Alexander Isak         Newcastle United     23
417            Chris Wood        Nottingham Forest     20
548         Matheus Cunha  Wolverhampton Wanderers     15

In [43]:
df[(df["Club"] == "Arsenal") & (df["Goals"] > 5)]

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
7,Gabriel Martinelli,Arsenal,Brazil,MID,33,2300,8,4,55,12,...,16,1,0,0,0%,0,0,0,0,0.0
11,Kai Havertz,Arsenal,Germany,FWD,23,1874,9,3,53,2,...,38,5,0,0,0%,0,0,0,0,0.0
13,Leandro Trossard,Arsenal,Belgium,MID,38,2550,8,7,72,2,...,27,2,1,0,0%,0,0,0,0,0.0
15,Mikel Merino,Arsenal,Spain,MID,28,1581,7,2,38,7,...,41,2,1,0,0%,0,0,0,0,0.0

In [47]:
df[(df["Club"] == "Liverpool") & (df["Assists"]>3)].sort_values(by="Assists", ascending=False) [["Player Name", "Club", "Goals", "Assists"]]

                Player Name       Club  Goals  Assists
324           Mohamed Salah  Liverpool     29       18
315      Dominik Szoboszlai  Liverpool      6        6
326  Trent Alexander-Arnold  Liverpool      3        6
306     Alexis Mac Allister  Liverpool      5        5
323               Luis Díaz  Liverpool      0        5
310              Cody Gakpo  Liverpool     10        4
325        Ryan Gravenberch  Liverpool      0        4

In [59]:
df.groupby("Club")["Goals"].sum().reset_index().sort_values(by="Goals", ascending=False)

                       Club  Goals
12                Liverpool     72
13          Manchester City     71
0                   Arsenal     67
15         Newcastle United     66
5    Brighton & Hove Albion     63
6                   Chelsea     63
1               Aston Villa     61
16        Nottingham Forest     57
3                 Brentford     54
7            Crystal Palace     51
18        Tottenham Hotspur     50
8                   Everton     41
9                    Fulham     41
20  Wolverhampton Wanderers     39
14        Manchester United     38
19          West Ham United     31
11           Leicester City     28
2               Bournemouth     24
17              Southampton     23
10             Ipswich Town     23
4                  Brighton      0

In [63]:
df[["Player Name", "Club", "Position"]]

         Player Name                     Club Position
0          Ben White                  Arsenal      DEF
1        Bukayo Saka                  Arsenal      MID
2         David Raya                  Arsenal      GKP
3        Declan Rice                  Arsenal      MID
4      Ethan Nwaneri                  Arsenal      MID
..               ...                      ...      ...
557   Santiago Bueno  Wolverhampton Wanderers      DEF
558         Tom King  Wolverhampton Wanderers      GKP
559      Tommy Doyle  Wolverhampton Wanderers      MID
560       Toti Gomes  Wolverhampton Wanderers      DEF
561  Yerson Mosquera  Wolverhampton Wanderers      DEF

[562 rows x 3 columns]

In [ ]:
df[df["Goals"]>15][["Player Name", "Goals"]]

        Player Name  Goals
46    Ollie Watkins     16
82     Bryan Mbeumo     20
107     Yoane Wissa     19
324   Mohamed Salah     29
335  Erling Haaland     22
391  Alexander Isak     23
417      Chris Wood     20

In [70]:
df[df["Club"] == "Manchester City"] [["Player Name", "Club"]]

              Player Name             Club
330    Abdukodir Khusanov  Manchester City
331        Bernardo Silva  Manchester City
332     Claudio Echeverri  Manchester City
333          Divin Mubama  Manchester City
334               Ederson  Manchester City
335        Erling Haaland  Manchester City
336        Ilkay Gündogan  Manchester City
337         Jack Grealish  Manchester City
338  Jahmai Simpson-Pusey  Manchester City
339          James McAtee  Manchester City
340           Jérémy Doku  Manchester City
341           John Stones  Manchester City
342        Josko Gvardiol  Manchester City
343       Kevin De Bruyne  Manchester City
344           Kyle Walker  Manchester City
345         Manuel Akanji  Manchester City
346         Mateo Kovacic  Manchester City
347         Matheus Nunes  Manchester City
348            Nathan Aké  Manchester City
349         Nico González  Manchester City
350         Nico O'Reilly  Manchester City
351         Omar Marmoush  Manchester City
352            Oscar Bobb  Manchester City
353            Phil Foden  Manchester City
354            Rico Lewis  Manchester City
355                 Rodri  Manchester City
356            Rúben Dias  Manchester City
357               Savinho  Manchester City
358         Stefan Ortega  Manchester City
359            Vitor Reis  Manchester City
360             Wes Burns  Manchester City

In [78]:
df.sort_values(by="Assists", ascending=False).head(15)[["Player Name", "Assists"]]

          Player Name  Assists
324     Mohamed Salah       18
399      Jacob Murphy       12
415    Anthony Elanga       11
99   Mikkel Damsgaard       10
45      Morgan Rogers       10
367   Bruno Fernandes       10
1         Bukayo Saka       10
222  Antonee Robinson       10
497     Son Heung-Min        9
514      Jarrod Bowen        8
14    Martin Ødegaard        8
357           Savinho        8
141       Cole Palmer        8
46      Ollie Watkins        8
177      Eberechi Eze        8

In [79]:
df.sort_values(by="Passes", ascending=False).head(1) [["Player Name", "Passes"]]

            Player Name  Passes
301  Victor Kristiansen    2923

In [5]:
df[(df["Position"] == "FWD") & (df["Goals"]>10) & (df["Assists"]>5)] [["Player Name", "Goals", "Assists"]]

      Player Name  Goals  Assists
46  Ollie Watkins     16        8

In [10]:
df.groupby("Club")["Goals"].mean().sort_values(ascending=False)

Club
Liverpool                  3.000000
Newcastle United           2.869565
Arsenal                    2.680000
Nottingham Forest          2.478261
Manchester City            2.290323
Aston Villa                2.259259
Brighton & Hove Albion     2.250000
Chelsea                    2.250000
Crystal Palace             1.961538
Brentford                  1.928571
Tottenham Hotspur          1.612903
Everton                    1.576923
Fulham                     1.576923
Manchester United          1.266667
Wolverhampton Wanderers    1.218750
West Ham United            1.107143
Leicester City             0.903226
Bournemouth                0.827586
Ipswich Town               0.766667
Southampton                0.676471
Brighton                   0.000000
Name: Goals, dtype: float64

In [12]:
df.groupby("Club")["Assists"].max().sort_values(ascending=False)

Club
Liverpool                  18
Newcastle United           12
Nottingham Forest          11
Arsenal                    10
Brentford                  10
Fulham                     10
Aston Villa                10
Manchester United          10
Tottenham Hotspur           9
Manchester City             8
West Ham United             8
Chelsea                     8
Crystal Palace              8
Wolverhampton Wanderers     7
Leicester City              5
Bournemouth                 5
Brighton & Hove Albion      4
Southampton                 4
Ipswich Town                4
Everton                     3
Brighton                    0
Name: Assists, dtype: int64

In [13]:
print(df.columns)

Index(['Player Name', 'Club', 'Nationality', 'Position', 'Appearances',
       'Minutes', 'Goals', 'Assists', 'Shots', 'Shots On Target',
       'Conversion %', 'Big Chances Missed', 'Hit Woodwork', 'Offsides',
       'Touches', 'Passes', 'Successful Passes', 'Passes%', 'Crosses',
       'Successful Crosses', 'Crosses %', 'fThird Passes',
       'Successful fThird Passes', 'fThird Passes %', 'Through Balls',
       'Carries', 'Progressive Carries', 'Carries Ended with Goal',
       'Carries Ended with Assist', 'Carries Ended with Shot',
       'Carries Ended with Chance', 'Possession Won', 'Dispossessed',
       'Clean Sheets', 'Clearances', 'Interceptions', 'Blocks', 'Tackles',
       'Ground Duels', 'gDuels Won', 'gDuels %', 'Aerial Duels', 'aDuels Won',
       'aDuels %', 'Goals Conceded', 'xGoT Conceded', 'Own Goals', 'Fouls',
       'Yellow Cards', 'Red Cards', 'Saves', 'Saves %', 'Penalties Saved',
       'Clearances Off Line', 'Punches', 'High Claims', 'Goals Prevented'],
      dtype='str')